"""add incident classification fields

Revision ID: 972d46c8fe5d
Revises: b9b269fd67b2
Create Date: 2026-09-19 16:35:03.109054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972d46c8fe5d'
down_revision: Union[str, Sequence[str], None] = 'b9b269fd67b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('incidents', sa.Column('classification_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'classification_reasoning')
    op.drop_column('incidents', 'classification_confidence')
    # ### end Alembic commands ###
