"""add duplicate candidate table

Revision ID: a7f44a9484ee
Revises: 972d46c8fe5d
Create Date: 2026-09-19 17:19:16.351180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f44a9484ee'
down_revision: Union[str, Sequence[str], None] = '972d46c8fe5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('possible_duplicate_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('matching_factors', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['possible_duplicate_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_candidates_id'), 'duplicate_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_incident_id'), 'duplicate_candidates', ['incident_id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_possible_duplicate_id'), 'duplicate_candidates', ['possible_duplicate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duplicate_candidates_possible_duplicate_id'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_incident_id'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_id'), table_name='duplicate_candidates')
    op.drop_table('duplicate_candidates')
    # ### end Alembic commands ###
