"""add recommendations and assignments

Revision ID: d42cf7d57ba3
Revises: d6f6968c2f04
Create Date: 2026-09-19 18:05:53.082963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42cf7d57ba3'
down_revision: Union[str, Sequence[str], None] = 'd6f6968c2f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_assignments_id'), 'resource_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_resource_assignments_incident_id'), 'resource_assignments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_resource_assignments_resource_id'), 'resource_assignments', ['resource_id'], unique=False)
    op.create_table('resource_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_recommendations_id'), 'resource_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_resource_recommendations_incident_id'), 'resource_recommendations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_resource_recommendations_resource_id'), 'resource_recommendations', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_recommendations_resource_id'), table_name='resource_recommendations')
    op.drop_index(op.f('ix_resource_recommendations_incident_id'), table_name='resource_recommendations')
    op.drop_index(op.f('ix_resource_recommendations_id'), table_name='resource_recommendations')
    op.drop_table('resource_recommendations')
    op.drop_index(op.f('ix_resource_assignments_resource_id'), table_name='resource_assignments')
    op.drop_index(op.f('ix_resource_assignments_incident_id'), table_name='resource_assignments')
    op.drop_index(op.f('ix_resource_assignments_id'), table_name='resource_assignments')
    op.drop_table('resource_assignments')
    # ### end Alembic commands ###
